export const ERROR_CODES = {
  USER: {
    NOT_FOUND: 'USER_NOT_FOUND',
    INVALID_USER_KEY: 'INVALID_USER_KEY',
    USER_KEY_REQUIRED: 'USER_KEY_REQUIRED',
    USERNAME_REQUIRED: 'USERNAME_REQUIRED',
    PHONE_NUMBER_REQUIRED: 'PHONE_NUMBER_REQUIRED',
    FULL_NAME_REQUIRED: 'FULL_NAME_REQUIRED',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  },
  CHAT: {
    ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
    MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
    USER_NOT_PARTICIPANT: 'USER_NOT_PARTICIPANT',
    INVALID_MESSAGE_TYPE: 'INVALID_MESSAGE_TYPE',
    CONTENT_TOO_LONG: 'CONTENT_TOO_LONG',
    FILE_TOO_LARGE: 'FILE_TOO_LARGE',
    UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
  },
  SOCKET: {
    AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
    INVALID_CONNECTION_DATA: 'INVALID_CONNECTION_DATA',
    CONNECTION_REJECTED: 'CONNECTION_REJECTED',
  },
  SYSTEM: {
    SOMETHING_WENT_WRONG: 'SOMETHING_WENT_WRONG',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
  },
} as const;

